### ISSUE TITLE
index.html left-sidebar not loading properly

### ISSUE THREAD

**Issue by chrisidakwo** [valarmoghulis/HTML5AdminTemplate#1]
The sidebar was not leading properly on different screen sizes; the arrangement of links were distorted.

A jQuery issue.

I already worked on it, and need to update it on the main repo. How do I do that?

**Comment by valarmoghulis** [comment]
- Send the code file to valarmoghulis@gmail.com & make sure to highlight the changes you have made
- I'll run some tests on your code
- On satisfactory result, I'll update you
- Make a new push request for the file in the dev branch
- The request will be accepted

Note I did not say master branch!
