### ISSUE TITLE
Difficult to open project on another IDE

### ISSUE THREAD

**Issue by chrisidakwo** [valarmoghulis/HTML5AdminTemplate#6]
I am finding it difficult to open the project ion another IDE other than Netbeans, I think it is important this is not an issue considering not all developers use Netbeans

**Comment by valarmoghulis** [comment]
I think this is an easy one.

But you should do it since you found it. An option is ignore the NBProject folder globally using ~/.gitignore_global

But if you know of any solution, please be sure to implement and make a pull request

**Comment by chrisidakwo** [comment]
I think this is an easy one.

But you should do it since you found it. An option is ignore the NBProject folder globally using ~/.gitignore_global

But if you know of any solution, please be sure to implement and upload the file to the dev branch

**Comment by valarmoghulis** [comment]
I think this is an easy one.

But you should do it since you found it. An option is ignore the NBProject folder globally using ~/.gitignore_global

But if you know of any solution, please be sure to implement and upload the file to the dev branch

**Comment by chrisidakwo** [comment]
Done!
